
try:
    print(x)
except NameError:
    print("Exception Handled")